development:
  adapter: postgresql
  encoding: unicode
  database: peruze_development
  pool: 5
  username: colton
  password: cookie12

test:
  adapter: postgresql
  encoding: unicode
  database: peruze_test
  pool: 5
  username: colton  
  password: cookie12

production:
  adapter: postgresql
  encoding: unicode
  database: peruze
  pool: 5
  username: colton  
  password: cookie12